# Generated by Django 5.2.5 on 2025-10-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_service_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
