# Generated by Django 5.2.5 on 2025-10-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_experience_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.CharField(help_text='E.g. Python, Django, HTML, CSS, JS', max_length=255, null=True),
        ),
    ]
