# Generated by Django 5.2.5 on 2025-10-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.TextField(blank=True, null=True),
        ),
    ]
